# Use official Node.js image as base
FROM node:22-alpine

# Set working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json into the container
COPY backend/package*.json ./

# Install dependencies
RUN npm install

# Copy the entire backend project into the container
COPY backend ./

# Expose the port on which your backend will run
EXPOSE 5000

# Command to run the application in staging
CMD ["npm", "run", "start"]
