# Utilisation de l'image officielle de Node.js
FROM node:22-alpine

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier package.json et package-lock.json dans le conteneur
COPY backend/package*.json ./

# Installer uniquement les dépendances de production
RUN npm install --production

# Copier l'ensemble du projet dans le conteneur
COPY backend ./

# Exposer le port 3000
EXPOSE 3000

# Commande pour démarrer l'application en mode production
CMD ["node", "app.js"]